import { SEED_OPPORTUNITIES } from "@/lib/services/sources/seed.data";

export const FALLBACK_EVENTS = [
  {
    _id: "fallback-event-1",
    title: "Build with AI Summit",
    slug: "build-with-ai-summit",
    description: "A hands-on event for builders exploring LLMs, agents, and real-world AI products.",
    overview: "Workshops, demos, and networking for developers shipping AI experiences.",
    image: "/images/event1.png",
    venue: "Online",
    location: "Online",
    date: "2026-06-15",
    time: "10:30 AM",
    mode: "online" as const,
    audience: "Students, developers, startup founders",
    agenda: ["Keynote", "Workshop", "Networking"],
    organizer: "DevEvent Community",
    tags: ["AI", "Workshop", "Online"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "fallback-event-2",
    title: "Open Source India Meetup",
    slug: "open-source-india-meetup",
    description: "Meet maintainers, contributors, and recruiters exploring the open-source ecosystem.",
    overview: "A community meetup focused on GitHub, contribution workflows, and open-source careers.",
    image: "/images/event2.png",
    venue: "Bengaluru Tech Hub",
    location: "Bangalore",
    date: "2026-06-22",
    time: "6:00 PM",
    mode: "offline" as const,
    audience: "Developers, students, maintainers",
    agenda: ["Panel", "Open-source demos", "Community networking"],
    organizer: "Open Source India",
    tags: ["Open Source", "Community", "Bangalore"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "fallback-event-3",
    title: "Cloud & DevOps Bootcamp",
    slug: "cloud-and-devops-bootcamp",
    description: "Build practical cloud automation skills using modern DevOps tools and pipelines.",
    overview: "A short bootcamp for developers preparing for real-world deployment workflows.",
    image: "/images/event3.png",
    venue: "Hybrid Studio",
    location: "Hybrid",
    date: "2026-07-03",
    time: "2:00 PM",
    mode: "hybrid" as const,
    audience: "Developers, students, cloud enthusiasts",
    agenda: ["CI/CD", "Kubernetes", "Scaling lessons"],
    organizer: "CloudSphere",
    tags: ["DevOps", "Cloud", "Hybrid"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const FALLBACK_OPPORTUNITIES = SEED_OPPORTUNITIES.slice(0, 8).map((item, index) => ({
  ...item,
  _id: `fallback-opp-${index + 1}`,
  views: 120 + index * 15,
  bookmarks: 18 + index,
  isExpired: false,
  isTrending: index < 3,
  createdAt: new Date(),
  updatedAt: new Date(),
}));
