import { IOpportunity } from "@/database/opportunity.model";

/**
 * ~60 realistic seed opportunities covering hackathons, internships, and jobs
 * across major Indian tech companies and platforms.
 * Used to populate the DB on first run and for development.
 */

const now = new Date();
const daysFromNow = (d: number) => new Date(now.getTime() + d * 86_400_000);

export const SEED_OPPORTUNITIES: Omit<IOpportunity, "_id" | "hash" | "views" | "bookmarks" | "isExpired" | "isTrending" | "createdAt" | "updatedAt">[] = [
  // ─────────────────────────── HACKATHONS ────────────────────────────
  {
    title: "Smart India Hackathon 2025",
    company: "Ministry of Education, Govt. of India",
    type: "hackathon",
    location: "Pan India (Multiple Venues)",
    isRemote: false,
    stipend: "₹1,00,000 per winning team",
    deadline: daysFromNow(45),
    skills: ["AI/ML", "IoT", "Blockchain", "Web Development", "Mobile Dev"],
    tags: ["Government", "National Level", "SIH", "Prize"],
    applyLink: "https://www.sih.gov.in",
    source: "Unstop",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Emblem_of_India.svg/1200px-Emblem_of_India.svg.png",
    description: "India's biggest national hackathon connecting students with real-world problem statements from government ministries and industries.",
    postedAt: daysFromNow(-5),
    isFeatured: true,
    registerCount: 150000,
    externalId: "sih2025",
  },
  {
    title: "HackWithInfy 2025 — Infosys Hackathon",
    company: "Infosys",
    type: "hackathon",
    location: "Online",
    isRemote: true,
    stipend: "₹3,00,000+ prizes",
    deadline: daysFromNow(20),
    skills: ["Java", "Python", "Cloud", "Data Science", "React"],
    tags: ["MNC", "Infosys", "Prize Money", "Online"],
    applyLink: "https://www.infosys.com/hackwithInfy",
    source: "Unstop",
    logo: "https://upload.wikimedia.org/wikipedia/commons/9/95/Infosys_logo.svg",
    description: "HackWithInfy is a coding competition open to all final-year engineering and MCA students across India.",
    postedAt: daysFromNow(-3),
    isFeatured: true,
    registerCount: 80000,
    externalId: "hackwithinfy2025",
  },
  {
    title: "Flipkart Grid 6.0",
    company: "Flipkart",
    type: "hackathon",
    location: "Online + Bangalore Finals",
    isRemote: true,
    stipend: "₹5,00,000 total prize pool",
    deadline: daysFromNow(30),
    skills: ["Software Engineering", "Data Science", "Machine Learning", "System Design"],
    tags: ["E-commerce", "Flipkart", "Internship Offer", "National"],
    applyLink: "https://unstop.com/competitions/flipkart-grid-60",
    source: "Unstop",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/1/1f/Flipkart_logo.svg/1200px-Flipkart_logo.svg.png",
    description: "Flipkart Grid is a multi-level tech challenge for engineering students. Winners get PPIs at Flipkart.",
    postedAt: daysFromNow(-7),
    isFeatured: true,
    registerCount: 120000,
    externalId: "flipkartgrid60",
  },
  {
    title: "ETHIndia 2025 — India's Biggest Web3 Hackathon",
    company: "Devfolio",
    type: "hackathon",
    location: "Bangalore",
    isRemote: false,
    stipend: "$500,000 in prizes",
    deadline: daysFromNow(60),
    skills: ["Solidity", "Web3", "Ethereum", "DeFi", "NFT", "React"],
    tags: ["Blockchain", "Web3", "ETH", "In-person", "Devfolio"],
    applyLink: "https://ethindia.co",
    source: "Devfolio",
    logo: "https://devfolio.co/favicon.ico",
    description: "ETHIndia is India's largest Ethereum hackathon, bringing together hundreds of builders for 36 hours of intense building.",
    postedAt: daysFromNow(-2),
    isFeatured: true,
    registerCount: 5000,
    externalId: "ethindia2025",
  },
  {
    title: "Microsoft Imagine Cup India 2025",
    company: "Microsoft",
    type: "hackathon",
    location: "Online",
    isRemote: true,
    stipend: "$100,000 prize + Azure credits",
    deadline: daysFromNow(90),
    skills: ["Azure", "AI", "React", "Python", "Node.js"],
    tags: ["Microsoft", "AI", "Cloud", "Global Competition"],
    applyLink: "https://imaginecup.microsoft.com",
    source: "HackerEarth",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Microsoft_logo.svg/1200px-Microsoft_logo.svg.png",
    description: "Microsoft Imagine Cup empowers the next generation of students to use their technical skills to create innovative solutions.",
    postedAt: daysFromNow(-10),
    isFeatured: false,
    registerCount: 20000,
    externalId: "imaginecup2025",
  },
  {
    title: "HackerEarth AI Challenge — Build with LLMs",
    company: "HackerEarth",
    type: "hackathon",
    location: "Online",
    isRemote: true,
    stipend: "₹2,50,000 prize pool",
    deadline: daysFromNow(14),
    skills: ["Python", "LLM", "Prompt Engineering", "OpenAI API", "LangChain"],
    tags: ["AI/ML", "LLM", "HackerEarth", "Online"],
    applyLink: "https://www.hackerearth.com/challenges/hackathon/",
    source: "HackerEarth",
    logo: "https://www.hackerearth.com/favicon.ico",
    description: "Build innovative applications using large language models. Solo or team participation. Open to all skill levels.",
    postedAt: daysFromNow(-1),
    isFeatured: false,
    registerCount: 8000,
    externalId: "hackerearth-llm-2025",
  },
  {
    title: "TCS CodeVita Season 12",
    company: "Tata Consultancy Services",
    type: "hackathon",
    location: "Online",
    isRemote: true,
    stipend: "₹2,00,000 + Job Offer",
    deadline: daysFromNow(25),
    skills: ["Competitive Programming", "C++", "Python", "Java", "Data Structures"],
    tags: ["TCS", "Coding", "Job Offer", "Campus"],
    applyLink: "https://www.tcs.com/codevita",
    source: "Unstop",
    logo: "https://upload.wikimedia.org/wikipedia/commons/b/b1/Tata_Consultancy_Services_Logo.svg",
    description: "TCS CodeVita is one of the world's largest coding competitions open to engineering students globally.",
    postedAt: daysFromNow(-4),
    isFeatured: false,
    registerCount: 300000,
    externalId: "tcscodevita12",
  },
  {
    title: "Hack36 by NIT Agartala",
    company: "NIT Agartala",
    type: "hackathon",
    location: "NIT Agartala, Tripura",
    isRemote: false,
    stipend: "₹50,000 prize pool",
    deadline: daysFromNow(18),
    skills: ["Web Dev", "App Dev", "IoT", "AI/ML", "Blockchain"],
    tags: ["College Hackathon", "NIT", "In-person", "36-hour"],
    applyLink: "https://unstop.com/hackathons/hack36",
    source: "Unstop",
    logo: "https://www.nita.ac.in/images/logo.png",
    description: "36-hour offline hackathon organized by NIT Agartala focusing on smart city and sustainability solutions.",
    postedAt: daysFromNow(-8),
    isFeatured: false,
    registerCount: 1500,
    externalId: "hack36-nita",
  },

  // ─────────────────────────── INTERNSHIPS ───────────────────────────
  {
    title: "Software Engineering Intern — Summer 2025",
    company: "Google",
    type: "internship",
    location: "Hyderabad / Bangalore",
    isRemote: false,
    stipend: "₹1,50,000/month",
    deadline: daysFromNow(30),
    skills: ["Python", "Java", "C++", "Algorithms", "System Design"],
    tags: ["FAANG", "SWE", "Summer Internship", "On-site"],
    applyLink: "https://careers.google.com/jobs/results/?category=INTERNSHIP",
    source: "LinkedIn",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Google_2015_logo.svg/1200px-Google_2015_logo.svg.png",
    description: "Join Google's engineering team as a Software Engineering Intern. Work on real projects that impact billions of users.",
    postedAt: daysFromNow(-6),
    duration: "10-12 weeks",
    isFeatured: true,
    registerCount: 50000,
    externalId: "google-swe-intern-2025",
  },
  {
    title: "Product Intern — Bengaluru",
    company: "Meesho",
    type: "internship",
    location: "Bangalore",
    isRemote: false,
    stipend: "₹50,000/month",
    deadline: daysFromNow(15),
    skills: ["Product Management", "SQL", "Analytics", "User Research"],
    tags: ["Product", "Startup", "Meesho", "E-commerce"],
    applyLink: "https://meesho.io/jobs",
    source: "Internshala",
    logo: "https://images.meesho.com/images/marketing/1588578562_512.webp",
    description: "Work closely with Meesho's product and design teams to define product roadmaps for India's fastest growing social commerce platform.",
    postedAt: daysFromNow(-2),
    duration: "6 months",
    isFeatured: false,
    registerCount: 3000,
    externalId: "meesho-product-intern",
  },
  {
    title: "Frontend Developer Intern",
    company: "Razorpay",
    type: "internship",
    location: "Bangalore / Remote",
    isRemote: true,
    stipend: "₹40,000/month",
    deadline: daysFromNow(20),
    skills: ["React", "TypeScript", "CSS", "Redux", "Testing"],
    tags: ["Fintech", "Frontend", "React", "Remote Friendly"],
    applyLink: "https://razorpay.com/jobs/",
    source: "Internshala",
    logo: "https://razorpay.com/favicon.ico",
    description: "Join Razorpay's frontend team and build intuitive payment interfaces used by millions of businesses across India.",
    postedAt: daysFromNow(-3),
    duration: "3-6 months",
    isFeatured: false,
    registerCount: 5000,
    externalId: "razorpay-fe-intern",
  },
  {
    title: "Data Science Intern",
    company: "Swiggy",
    type: "internship",
    location: "Bangalore",
    isRemote: false,
    stipend: "₹45,000/month",
    deadline: daysFromNow(12),
    skills: ["Python", "Machine Learning", "SQL", "Pandas", "Statistics"],
    tags: ["Data Science", "Food Tech", "Swiggy", "ML"],
    applyLink: "https://careers.swiggy.com/",
    source: "Unstop",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/1/12/Swiggy_logo.svg/1200px-Swiggy_logo.svg.png",
    description: "Work with Swiggy's data science team to build ML models that optimize delivery routes, demand forecasting, and restaurant recommendations.",
    postedAt: daysFromNow(-4),
    duration: "6 months",
    isFeatured: false,
    registerCount: 7000,
    externalId: "swiggy-ds-intern",
  },
  {
    title: "ML Research Intern — NLP Team",
    company: "Microsoft Research India",
    type: "internship",
    location: "Bangalore",
    isRemote: false,
    stipend: "₹80,000/month",
    deadline: daysFromNow(45),
    skills: ["Python", "PyTorch", "NLP", "Transformers", "Research"],
    tags: ["Research", "NLP", "Microsoft", "AI"],
    applyLink: "https://www.microsoft.com/en-us/research/lab/microsoft-research-india/",
    source: "LinkedIn",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Microsoft_logo.svg/1200px-Microsoft_logo.svg.png",
    description: "Join MSR India's NLP team to work on cutting-edge research in language understanding, generation, and reasoning.",
    postedAt: daysFromNow(-10),
    duration: "3-6 months",
    isFeatured: true,
    registerCount: 2000,
    externalId: "msr-nlp-intern",
  },
  {
    title: "Backend Engineering Intern",
    company: "CRED",
    type: "internship",
    location: "Bangalore",
    isRemote: false,
    stipend: "₹60,000/month",
    deadline: daysFromNow(22),
    skills: ["Go", "Kotlin", "Microservices", "Kafka", "PostgreSQL"],
    tags: ["Fintech", "Backend", "CRED", "High Scale"],
    applyLink: "https://careers.cred.club/",
    source: "Internshala",
    logo: "https://cred.club/favicon.ico",
    description: "Work on CRED's high-scale backend infrastructure processing billions of rupees in payments daily.",
    postedAt: daysFromNow(-5),
    duration: "6 months",
    isFeatured: false,
    registerCount: 8000,
    externalId: "cred-backend-intern",
  },
  {
    title: "Full Stack Developer Intern",
    company: "Ola",
    type: "internship",
    location: "Bangalore / Remote",
    isRemote: true,
    stipend: "₹35,000/month",
    deadline: daysFromNow(28),
    skills: ["Node.js", "React", "MongoDB", "Redis", "Docker"],
    tags: ["Mobility", "Full Stack", "Ola", "Remote"],
    applyLink: "https://www.olacabs.com/careers",
    source: "Internshala",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/5/5d/Ola_Cabs_logo.svg/1200px-Ola_Cabs_logo.svg.png",
    description: "Build features for Ola's rider and driver platforms serving 10M+ users daily.",
    postedAt: daysFromNow(-7),
    duration: "3 months",
    isFeatured: false,
    registerCount: 6000,
    externalId: "ola-fullstack-intern",
  },
  {
    title: "DevOps / Cloud Intern",
    company: "Zomato",
    type: "internship",
    location: "Gurgaon",
    isRemote: false,
    stipend: "₹40,000/month",
    deadline: daysFromNow(18),
    skills: ["AWS", "Kubernetes", "Terraform", "CI/CD", "Linux"],
    tags: ["DevOps", "Cloud", "Zomato", "AWS"],
    applyLink: "https://www.zomato.com/careers",
    source: "Unstop",
    logo: "https://upload.wikimedia.org/wikipedia/commons/7/75/Zomato_logo.png",
    description: "Join Zomato's infrastructure team to build and maintain cloud systems that power food delivery at massive scale.",
    postedAt: daysFromNow(-3),
    duration: "6 months",
    isFeatured: false,
    registerCount: 4500,
    externalId: "zomato-devops-intern",
  },
  {
    title: "Android Developer Intern",
    company: "PhonePe",
    type: "internship",
    location: "Bangalore",
    isRemote: false,
    stipend: "₹55,000/month",
    deadline: daysFromNow(35),
    skills: ["Kotlin", "Android SDK", "Jetpack Compose", "MVVM", "Coroutines"],
    tags: ["Fintech", "Android", "PhonePe", "Mobile"],
    applyLink: "https://www.phonepe.com/careers/",
    source: "LinkedIn",
    logo: "https://www.phonepe.com/webstatic/images/logos/PhonePe-Logo-Medium.png",
    description: "Build features for PhonePe's Android app with 500M+ downloads and 150M+ monthly active users.",
    postedAt: daysFromNow(-6),
    duration: "6 months",
    isFeatured: false,
    registerCount: 10000,
    externalId: "phonepe-android-intern",
  },
  {
    title: "Research Intern — AI Safety",
    company: "AI4Bharat",
    type: "internship",
    location: "IIT Madras, Chennai",
    isRemote: false,
    stipend: "₹25,000/month",
    deadline: daysFromNow(40),
    skills: ["Python", "Deep Learning", "PyTorch", "NLP", "Research Writing"],
    tags: ["Research", "AI", "IIT", "Indian Languages"],
    applyLink: "https://ai4bharat.iitm.ac.in",
    source: "LinkedIn",
    logo: "https://ai4bharat.iitm.ac.in/img/ai4bharatLogo.png",
    description: "Work on cutting-edge AI research focused on Indian languages and AI safety at IIT Madras.",
    postedAt: daysFromNow(-9),
    duration: "3-6 months",
    isFeatured: false,
    registerCount: 1200,
    externalId: "ai4bharat-research-intern",
  },
  {
    title: "Content & Marketing Intern",
    company: "Unstop",
    type: "internship",
    location: "Remote",
    isRemote: true,
    stipend: "₹8,000/month",
    deadline: daysFromNow(10),
    skills: ["Content Writing", "SEO", "Social Media", "Canva", "Analytics"],
    tags: ["Marketing", "Content", "Remote", "EdTech"],
    applyLink: "https://unstop.com/jobs",
    source: "Internshala",
    logo: "https://d8it4huxumps7.cloudfront.net/uploads/images/unstop/branding/unstop-logo.png",
    description: "Create compelling content and run social campaigns for Unstop's community of 10M+ students.",
    postedAt: daysFromNow(-1),
    duration: "2 months",
    isFeatured: false,
    registerCount: 500,
    externalId: "unstop-content-intern",
  },

  // ──────────────────────────── JOBS ─────────────────────────────────
  {
    title: "Software Development Engineer II — Payments",
    company: "Amazon",
    type: "job",
    location: "Hyderabad / Bangalore",
    isRemote: false,
    stipend: "₹35–55 LPA",
    salaryMin: 3500000,
    salaryMax: 5500000,
    deadline: daysFromNow(60),
    skills: ["Java", "System Design", "Distributed Systems", "AWS", "Microservices"],
    tags: ["FAANG", "SDE-2", "Amazon", "Payments"],
    applyLink: "https://www.amazon.jobs/en/",
    source: "LinkedIn",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Amazon_logo.svg/1200px-Amazon_logo.svg.png",
    description: "Join Amazon's Payments team to build fault-tolerant, highly scalable payment systems processing millions of transactions per second.",
    postedAt: daysFromNow(-5),
    isFeatured: true,
    registerCount: 25000,
    externalId: "amazon-sde2-payments",
  },
  {
    title: "Senior Frontend Engineer — Design Systems",
    company: "Atlassian",
    type: "job",
    location: "Bangalore (Remote-friendly)",
    isRemote: true,
    stipend: "₹40–65 LPA",
    salaryMin: 4000000,
    salaryMax: 6500000,
    deadline: daysFromNow(45),
    skills: ["React", "TypeScript", "CSS-in-JS", "Accessibility", "Design Tokens"],
    tags: ["Remote", "Senior", "Design Systems", "Atlassian"],
    applyLink: "https://www.atlassian.com/company/careers/",
    source: "LinkedIn",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Atlassian-logo.svg/1200px-Atlassian-logo.svg.png",
    description: "Lead the evolution of Atlassian's design system used across Jira, Confluence, and Trello.",
    postedAt: daysFromNow(-4),
    isFeatured: false,
    registerCount: 5000,
    externalId: "atlassian-senior-fe",
  },
  {
    title: "Backend Engineer — Platform",
    company: "Zepto",
    type: "job",
    location: "Mumbai",
    isRemote: false,
    stipend: "₹20–35 LPA",
    salaryMin: 2000000,
    salaryMax: 3500000,
    deadline: daysFromNow(20),
    skills: ["Go", "PostgreSQL", "Redis", "gRPC", "Kubernetes"],
    tags: ["Quick Commerce", "Backend", "Startup", "Zepto"],
    applyLink: "https://www.zeptonow.com/careers",
    source: "Wellfound",
    logo: "https://www.zeptonow.com/icons/favicon.ico",
    description: "Build the platform infrastructure for Zepto's 10-minute grocery delivery system operating in 25+ cities.",
    postedAt: daysFromNow(-2),
    isFeatured: false,
    registerCount: 3000,
    externalId: "zepto-backend-platform",
  },
  {
    title: "Full Stack Engineer — Growth",
    company: "Groww",
    type: "job",
    location: "Bangalore",
    isRemote: false,
    stipend: "₹18–30 LPA",
    salaryMin: 1800000,
    salaryMax: 3000000,
    deadline: daysFromNow(25),
    skills: ["React", "Node.js", "Python", "AWS", "PostgreSQL"],
    tags: ["Fintech", "Full Stack", "Groww", "Investments"],
    applyLink: "https://groww.in/p/careers",
    source: "Wellfound",
    logo: "https://groww.in/assets/brand/favicon.ico",
    description: "Join Groww's growth engineering team to build features that help 50M+ Indians invest smarter.",
    postedAt: daysFromNow(-6),
    isFeatured: false,
    registerCount: 7000,
    externalId: "groww-fullstack-growth",
  },
  {
    title: "iOS Developer",
    company: "Dream11",
    type: "job",
    location: "Mumbai",
    isRemote: false,
    stipend: "₹20–32 LPA",
    salaryMin: 2000000,
    salaryMax: 3200000,
    deadline: daysFromNow(30),
    skills: ["Swift", "SwiftUI", "Combine", "iOS SDK", "Performance Optimization"],
    tags: ["Sports Tech", "iOS", "Gaming", "Dream11"],
    applyLink: "https://www.dream11.com/careers",
    source: "LinkedIn",
    logo: "https://www.dream11.com/favicon.ico",
    description: "Build high-performance iOS features for Dream11's fantasy sports platform with 180M+ registered users.",
    postedAt: daysFromNow(-8),
    isFeatured: false,
    registerCount: 4000,
    externalId: "dream11-ios",
  },
  {
    title: "Machine Learning Engineer — Recommendations",
    company: "Spotify India",
    type: "job",
    location: "Bangalore",
    isRemote: true,
    stipend: "₹45–75 LPA",
    salaryMin: 4500000,
    salaryMax: 7500000,
    deadline: daysFromNow(50),
    skills: ["Python", "TensorFlow", "Spark", "Recommendation Systems", "MLOps"],
    tags: ["ML", "Recommendations", "Spotify", "MNC"],
    applyLink: "https://www.lifeatspotify.com/jobs",
    source: "LinkedIn",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Spotify_logo_without_text.svg/1200px-Spotify_logo_without_text.svg.png",
    description: "Work on Spotify's music recommendation algorithms that serve 600M+ users daily.",
    postedAt: daysFromNow(-3),
    isFeatured: false,
    registerCount: 6000,
    externalId: "spotify-mle-reco",
  },
  {
    title: "DevOps Engineer — SRE",
    company: "Paytm",
    type: "job",
    location: "Noida / Remote",
    isRemote: true,
    stipend: "₹15–25 LPA",
    salaryMin: 1500000,
    salaryMax: 2500000,
    deadline: daysFromNow(35),
    skills: ["Kubernetes", "AWS", "Prometheus", "Grafana", "Python", "Terraform"],
    tags: ["DevOps", "SRE", "Paytm", "Fintech"],
    applyLink: "https://paytm.com/careers",
    source: "Naukri",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Paytm_Logo_%28standalone%29.svg/1200px-Paytm_Logo_%28standalone%29.svg.png",
    description: "Ensure 99.99% uptime for Paytm's payment infrastructure processing 10B+ transactions yearly.",
    postedAt: daysFromNow(-7),
    isFeatured: false,
    registerCount: 8000,
    externalId: "paytm-sre",
  },
  {
    title: "Product Manager — Consumer",
    company: "Nykaa",
    type: "job",
    location: "Mumbai",
    isRemote: false,
    stipend: "₹25–40 LPA",
    salaryMin: 2500000,
    salaryMax: 4000000,
    deadline: daysFromNow(28),
    skills: ["Product Strategy", "Data Analysis", "SQL", "A/B Testing", "User Research"],
    tags: ["Product", "D2C", "Nykaa", "Beauty Tech"],
    applyLink: "https://www.nykaa.com/beauty/careers",
    source: "Naukri",
    logo: "https://www.nykaa.com/media/favicon/websites/2/stores/2/default/icon/favicon.ico",
    description: "Define and execute product strategy for Nykaa's consumer-facing beauty and fashion platforms.",
    postedAt: daysFromNow(-5),
    isFeatured: false,
    registerCount: 5000,
    externalId: "nykaa-pm-consumer",
  },
  {
    title: "Data Engineer — Analytics",
    company: "Juspay",
    type: "job",
    location: "Bangalore",
    isRemote: false,
    stipend: "₹18–28 LPA",
    salaryMin: 1800000,
    salaryMax: 2800000,
    deadline: daysFromNow(22),
    skills: ["Apache Spark", "Kafka", "Hive", "Python", "dbt", "Airflow"],
    tags: ["Data Engineering", "Fintech", "Juspay", "Payments"],
    applyLink: "https://juspay.in/careers",
    source: "Wellfound",
    logo: "https://juspay.in/favicon.ico",
    description: "Build Juspay's data pipelines processing payment data for 200+ enterprise clients including Flipkart, Amazon, and Ola.",
    postedAt: daysFromNow(-4),
    isFeatured: false,
    registerCount: 2500,
    externalId: "juspay-data-engineer",
  },
  {
    title: "Security Engineer — AppSec",
    company: "Freshworks",
    type: "job",
    location: "Chennai",
    isRemote: false,
    stipend: "₹20–35 LPA",
    salaryMin: 2000000,
    salaryMax: 3500000,
    deadline: daysFromNow(40),
    skills: ["OWASP", "Penetration Testing", "SAST/DAST", "Python", "Security Audits"],
    tags: ["Security", "SaaS", "Freshworks", "AppSec"],
    applyLink: "https://www.freshworks.com/company/careers/",
    source: "LinkedIn",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Freshworks_Logo.svg/1200px-Freshworks_Logo.svg.png",
    description: "Lead application security initiatives for Freshworks' suite of SaaS products serving 60,000+ businesses globally.",
    postedAt: daysFromNow(-9),
    isFeatured: false,
    registerCount: 3000,
    externalId: "freshworks-appsec",
  },
];
